### ISSUE TITLE
Not loading lists.

### ISSUE THREAD

**Issue by QB3L** [TehCrucible/rawrANIME.bundle#5]

**Comment by QB3L** [comment]
I think that since they updated their website the parsing of this bundle got broken.

**Comment by TehCrucible** [comment]
Thanks QB3L, I am aware of this and working with the site developers to get it sorted in the near future.  I'm going to close this issue as there is already an issue open that you can contribute to here:

https://github.com/TehCrucible/rawrANIME.bundle/issues/3#issuecomment-146989043
